# Platform
TARGET_BOARD_PLATFORM := gxl
TARGET_BOARD_PLATFORM_GPU := mali-450
# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a7
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := gxl
# Kernel
TARGET_PREBUILT_KERNEL := device/212/minim8s/kernel
#BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE := 0x01078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --second_offset 0xffe88000 --ramdisk_offset 0xfff88000 --tags_offset 0xfef88100 --second device/212/minim8s/second
# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x02000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x02000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
BOARD_CACHEIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5206179840
BOARD_FLASH_BLOCK_SIZE := 131072
# Recovery
TARGET_RECOVERY_FSTAB := device/212/minim8s/twrp.fstab
TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
TARGET_RECOVERY_FORCE_PIXEL_FORMAT := "RGB_565"
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SUPPRESS_SECURE_ERASE := true
#BOARD_HAS_LARGE_FILESYSTEM := true
#BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
#BOARD_SUPPRESS_EMMC_WIPE := true
# TWRP
TW_NO_SCREEN_TIMEOUT := true
#HAVE_SELINUX := true
TW_DEFAULT_LANGUAGE := ru
TW_SKIP_MD5_GENERATE_VAR := true
TW_MILITARY_TIME := true
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_CRYPTO := true
TW_NO_BATT_PERCENT := true
TW_NO_REBOOT_BOOTLOADER := true
TW_THEME := landscape_hdpi
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
#RECOVERY_SDCARD_ON_DATA := true
